### ISSUE TITLE
使用 docker-compose 部署，未能成功

### ISSUE THREAD

**Issue by abeelan** [wuranxu/pity#99]
文档中的启动命令
> docker-compose -f .\ops\docker-compose.yaml up

Ubuntu 环境中，需要替换 `\` 为 `/` 再运行。

运行后出现报错：
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/34361264/227428719-260f0c1f-1b24-4b4f-8ab9-2178051639ab.png">

**Comment by abeelan** [comment]
docker-compose.yml 文件中：
```yml
...
user:
    build:
      context: ../
      dockerfile: app/v1/service/user/dockerfile  # 这个 dockerfile 缺失
    container_name: pity_user
...
```
